### PR TITLE
Format unformatted code

### PR DESCRIPTION
**Pull request by ceciliasaraiva**
It seems some people don't have the git pre-commit hook properly. 😢 As a result, we got a lot of code not following the agreed rules we have set up and sometimes this end up meaning we get the correct formatting in other people's PRs when they touch an unformatted file, which ends up polluting their PRs.
Therefore, in this PR, I run the formatter in whole code - apart from generated code.

### CODE REVIEW

**Review by emin-grbo — APPROVED** [review]
Superb! Lookin' good!

**Comment by emin-grbo** [comment]
🧹

**Review by bkdl — APPROVED** [review]

**Review by asendra — APPROVED** [review]
Can we use the `.git-blame-ignore-revs` for this?

**Comment by ceciliasaraiva** [comment]
> Can we use the `.git-blame-ignore-revs` for this?

Good idea. It's not set up here, I'll create a ticket for us and we can add it when it is done.

**Pull request merged**
