### PR TITLE
Playlog tests: Align skipToNext behavior with Android: don't do anything when there's no nextItem set up

### PR DESCRIPTION
**Pull request by ceciliasaraiva**
In order to fix the playlog tests, we need to address one of the different behaviors observed. So in this PR we address this different behavior - used by new playlog tests coming up in next PRs.

⚠️ The functionality itself (skip to next) is still under testing and therefore under control in case of any issues - the reason why I haven't added a FF.

⚠️ We can only run all player tests in all PRs again after this set of PRs are merged and we fix known existing flakiness.

---

This pull request includes changes to the `PlayerEngine` class in the `PlayerEngine.swift` file to streamline the `skipToNext` method and improve code readability.

Code simplification:

* [`Sources/Player/PlaybackEngine/PlayerEngine.swift`](diffhunk://#diff-e72feb354eac41dcce7baa31a6b2455945960a35c569f3ab640daa0e629a2015L184-R187): Simplified the `skipToNext` method by combining the assignment and the `guard` statement for `playerItem`, ensuring the current item is unloaded only when the next item is available.

### CODE REVIEW

**Review by asendra — COMMENTED** [review]
Are we sure this is desired behaviour?

Before skip to next, the client would either load the next item into Player, or, if there is no next item, do something else I guess?

With this change, the next button will do nothing if there is no next track, right? (this can be tested if you disable `Autoplay` ang go to the last item in the queue)

Or is the button disabled, so there is no way for the client to call `skipToNext` in that case?

**Comment by ceciliasaraiva** [comment]
> Are we sure this is desired behaviour?
> 
> Before skip to next, the client would either load the next item into Player, or, if there is no next item, do something else I guess?
> 
> With this change, the next button will do nothing if there is no next track, right? (this can be tested if you disable `Autoplay` ang go to the last item in the queue)
> 
> Or is the button disabled, so there is no way for the client to call `skipToNext` in that case?

This was a bug found during playlog tests based on their definition.

I believe it works the same way as if next is called when there is no next item. I suppose clients need to address if they want a different behavior, which I guess we don't, and that can be discussed separately.

**Review by emin-grbo — APPROVED** [review]
👍

**Review by asendra — APPROVED** [review]
As discussed, better to align on this, an this is a case that should not happen in our client because next button will be disabled.

**Pull request merged**
